# permissions for end users to view secretboxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretbox-viewer-role
rules:
- apiGroups:
  - secretbox.ipvl.de
  resources:
  - secretboxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secretbox.ipvl.de
  resources:
  - secretboxes/status
  verbs:
  - get
