# permissions for end users to edit secretboxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretbox-editor-role
rules:
- apiGroups:
  - secretbox.ipvl.de
  resources:
  - secretboxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secretbox.ipvl.de
  resources:
  - secretboxes/status
  verbs:
  - get
